/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _boardThread$schema = z.object({
  id: z.string(),
  title: z.string(),
  summary: z.string(),
  status: z.string(),
  steps: z.number(),
  doneSteps: z.number(),
  lastAdvanceBy: z.string(),
  updatedAt: z.number(),
  ageDays: z.number(),
  isCandidate: z.boolean(),
})

const _listResult$schema = z.array(_boardThread$schema)

export const TYPERT = {
  package: '@deepseek-ai/dsh-client-coral-board',
  face: 'host',
  schemas: [
    { name: 'BoardThread', schema: _boardThread$schema },
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-client-coral-board#board/list',
      service: 'board',
      namespace: 'board',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-client-coral-board/types#BoardThread[]',
        schema: _listResult$schema,
      },
      sourceLocation: { file: 'packages/client/coral-board/src/index.ts', line: 61, column: 3 },
    },
  ],
  model: {
    services: [
      {
        description: 'The `board` Remote service: read-only thread board projection.',
        summary: 'The `board` Remote service.',
        tags: [],
        jsDoc: '/** The `board` Remote service: read-only thread board projection. */',
        key: 'board',
        exportName: 'BoardService',
        members: [
          { kind: 'method', name: 'list', signature: 'list(): Promise<BoardThread[]>', summary: 'List all threads with projected board rows (active first, newest first).' },
        ],
        types: [
          { name: 'BoardThread', declaration: 'export interface BoardThread { readonly id: string; readonly title: string; readonly summary: string; readonly status: string; readonly steps: number; readonly doneSteps: number; readonly lastAdvanceBy: string; readonly updatedAt: number; readonly ageDays: number; readonly isCandidate: boolean; }' },
        ],
      },
    ],
    events: [],
    objects: [],
  },
}
