/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _balanceEntry$schema = z.object({
  id: z.string(),
  label: z.string(),
  kind: z.union([z.literal('deepseek'), z.literal('custom')]),
  baseUrl: z.string().optional(),
  balanceUrl: z.string().optional(),
  apiKey: z.string().optional(),
  credential: z.string().optional(),
})

const _balanceEntryInput$schema = _balanceEntry$schema.omit({ id: true })

const _balanceEntryPatch$schema = z.object({
  label: z.string().optional(),
  kind: z.union([z.literal('deepseek'), z.literal('custom')]).optional(),
  baseUrl: z.string().optional(),
  balanceUrl: z.string().optional(),
  apiKey: z.string().optional(),
  credential: z.string().optional(),
})

const _balanceInfo$schema = z.object({
  currency: z.string(),
  total: z.string(),
})

const _balanceResult$schema = z.object({
  id: z.string(),
  label: z.string(),
  ok: z.boolean(),
  available: z.boolean().optional(),
  infos: z.array(_balanceInfo$schema).optional(),
  error: z.string().optional(),
  updatedAt: z.number(),
})

const _listResult$schema = z.array(_balanceEntry$schema)
const _queryResult$schema = z.array(_balanceResult$schema)
const _addResult$schema = z.array(_balanceEntry$schema)
const _removeResult$schema = z.array(_balanceEntry$schema)
const _updateResult$schema = z.array(_balanceEntry$schema)

export const TYPERT = {
  package: '@deepseek-ai/dsh-client-ui-balance',
  face: 'host',
  schemas: [
    { name: 'BalanceEntry', schema: _balanceEntry$schema },
    { name: 'BalanceEntryInput', schema: _balanceEntryInput$schema },
    { name: 'BalanceEntryPatch', schema: _balanceEntryPatch$schema },
    { name: 'BalanceInfo', schema: _balanceInfo$schema },
    { name: 'BalanceResult', schema: _balanceResult$schema },
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-client-ui-balance#balance/list',
      service: 'balance',
      namespace: 'balance',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-client-ui-balance/types#BalanceEntry[]',
        schema: _listResult$schema,
      },
      sourceLocation: { file: 'packages/client/ui-balance/src/index.ts', line: 47, column: 3 },
    },
    {
      id: '@deepseek-ai/dsh-client-ui-balance#balance/query',
      service: 'balance',
      namespace: 'balance',
      method: 'query',
      invocation: { kind: 'direct' },
      parameters: [],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-client-ui-balance/types#BalanceResult[]',
        schema: _queryResult$schema,
      },
      sourceLocation: { file: 'packages/client/ui-balance/src/index.ts', line: 53, column: 3 },
    },
    {
      id: '@deepseek-ai/dsh-client-ui-balance#balance/add',
      service: 'balance',
      namespace: 'balance',
      method: 'add',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'entry',
          wire: 'entry',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-client-ui-balance/types#BalanceEntryInput',
            schema: _balanceEntryInput$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-client-ui-balance/types#BalanceEntry[]',
        schema: _addResult$schema,
      },
      sourceLocation: { file: 'packages/client/ui-balance/src/index.ts', line: 64, column: 3 },
    },
    {
      id: '@deepseek-ai/dsh-client-ui-balance#balance/remove',
      service: 'balance',
      namespace: 'balance',
      method: 'remove',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: { mode: 'strict', typeSymbol: 'string', schema: z.string() },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-client-ui-balance/types#BalanceEntry[]',
        schema: _removeResult$schema,
      },
      sourceLocation: { file: 'packages/client/ui-balance/src/index.ts', line: 79, column: 3 },
    },
    {
      id: '@deepseek-ai/dsh-client-ui-balance#balance/update',
      service: 'balance',
      namespace: 'balance',
      method: 'update',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: { mode: 'strict', typeSymbol: 'string', schema: z.string() },
        },
        {
          name: 'patch',
          wire: 'patch',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-client-ui-balance/types#BalanceEntryInput (partial)',
            schema: _balanceEntryPatch$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-client-ui-balance/types#BalanceEntry[]',
        schema: _updateResult$schema,
      },
      sourceLocation: { file: 'packages/client/ui-balance/src/index.ts', line: 89, column: 3 },
    },
  ],
  model: {
    services: [
      {
        description: 'The `balance` Remote service: store CRUD + query, all session-free.',
        summary: 'The `balance` Remote service.',
        tags: [],
        jsDoc: '/** The `balance` Remote service: store CRUD + query, all session-free. */',
        key: 'balance',
        exportName: 'BalanceService',
        members: [
          { kind: 'method', name: 'list', signature: 'list(): Promise<BalanceEntry[]>', summary: 'List configured entries; inline keys are never echoed.' },
          { kind: 'method', name: 'query', signature: 'query(): Promise<BalanceResult[]>', summary: 'Query every configured entry and return per-entry outcomes.' },
          { kind: 'method', name: 'add', signature: 'add(entry: BalanceEntryInput): Promise<BalanceEntry[]>', summary: 'Add one API entry and return the fresh (secrets-stripped) list.' },
          { kind: 'method', name: 'remove', signature: 'remove(id: string): Promise<BalanceEntry[]>', summary: 'Remove one API entry and return the fresh list.' },
          { kind: 'method', name: 'update', signature: 'update(id: string, patch: Partial<BalanceEntryInput>): Promise<BalanceEntry[]>', summary: 'Patch one API entry and return the fresh list.' },
        ],
        types: [
          { name: 'BalanceEntry', declaration: 'export interface BalanceEntry { readonly id: string; readonly label: string; readonly kind: "deepseek" | "custom"; readonly baseUrl?: string; readonly balanceUrl?: string; readonly apiKey?: string; readonly credential?: string; }' },
          { name: 'BalanceEntryInput', declaration: 'export type BalanceEntryInput = Omit<BalanceEntry, "id">;' },
          { name: 'BalanceResult', declaration: 'export interface BalanceResult { readonly id: string; readonly label: string; readonly ok: boolean; readonly available?: boolean; readonly infos?: BalanceInfo[]; readonly error?: string; readonly updatedAt: number; }' },
          { name: 'BalanceInfo', declaration: 'export interface BalanceInfo { readonly currency: string; readonly total: string; }' },
        ],
      },
    ],
    events: [],
    objects: [],
  },
}
